name: Make releases

on:
  push:
    tags:
      - "0.*"
      - "1.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies and build styles
        run: |
          npm ci
          gulp css

      - name: Get Version
        shell: bash
        id: get-version
        run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"

      - name: Create installable system zip file
        run:  zip -r tinyd6.zip *

      - name: Create release
        id: create_versioned_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.get-version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./system.json,./tinyd6.zip"
